services:
  PermiTask-Database:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=permitask
    ports:
      - 5432:5432
